### ISSUE TITLE
[Bug] host goal state processing error not propagated from DPM to Port manager 

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor#273]
__Context__
When Alcor Control Agent processs the goal state message from Alcor Controller, it could return an error for a particular (port) state configuration. The success and error of each state configuration is passed to DPM.

__Expected:__
When ACA return an error for one of the state configuration, the error is sent to DPM. We expect the error is propagated to port manager so that it can show the error to the caller.

__Actual:__
When ACA return an error for one of the state configuration, the error is sent to DPM. The error is not propagated to port manager and it still returns success to the caller.

**Comment by xieus** [comment]
Thanks for raising the error. 

Assigned to @haboy52581 to address as part of PR #https://github.com/futurewei-cloud/alcor/pull/240. 

@haboy52581 Please link PR #https://github.com/futurewei-cloud/alcor/pull/240 to this ticket when the fix is committed. This way, when the PR is merged, this ticket will get closed automatically.

**Comment by haboy52581** [comment]
#240 linked

**Comment by haboy52581** [comment]
fixed in 3f9c448

**Comment by haboy52581** [comment]
since this one is fixed for long time, I would close this

**Comment by er1cthe0ne** [comment]
reopening per discussion. Issue is not fully fixed, let's revisit it.

**Comment by xieus** [comment]
I don't quite remember the detail of this issue. Can we put some more details? @er1cthe0ne @haboy52581

**Comment by haboy52581** [comment]
this is already fixed in current dpm

**Comment by xieus** [comment]
Issue closed.
